# Generated by Django 3.2.20 on 2025-02-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanrecord',
            name='document',
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='matched_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matched_docs', to='users.document'),
        ),
        migrations.AddField(
            model_name='scanrecord',
            name='scanned_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scanned_docs', to='users.document'),
        ),
    ]
