# Generated by Django 3.2.20 on 2025-02-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250219_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0),
        ),
    ]
